# Dependabot configuration for keeping dependencies up to date
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # Swift Package Manager (Tuist dependencies)
  - package-ecosystem: "swift"
    directory: "/Tuist"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    
  # Swift Package Manager (root level if needed)
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 3