name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    name: Code Quality
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Install SwiftFormat
      run: brew install swiftformat
      
    - name: SwiftLint
      run: swiftlint --strict
      
    - name: SwiftFormat Check
      run: swiftformat --lint .

  build-and-test:
    name: Build & Test
    runs-on: macos-15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: Install Tuist
      run: |
        brew install --formula tuist
        tuist --version
        
    - name: Cache Tuist dependencies
      uses: actions/cache@v4
      with:
        path: |
          Tuist/.build
          ~/.cache/tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('Tuist/Package.swift', 'Tuist/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-tuist-
      
    - name: Install dependencies
      run: tuist install
      
    - name: Generate Xcode project
      run: tuist generate --no-open
      
    - name: Build app with Tuist
      run: tuist build App
      
    - name: Run tests (iPhone 15 targeting)
      run: |
        xcodebuild test \
          -workspace iOSClaudeCodeStarter.xcworkspace \
          -scheme App \
          -destination 'platform=iOS Simulator,name=iPhone 15' \
          -resultBundlePath test-results.xcresult
      
    - name: Check for uncommitted changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ Uncommitted changes detected after tuist generate:"
          git status --porcelain
          echo "Run 'tuist generate' and commit the changes."
          exit 1
        else
          echo "✅ No uncommitted changes detected."
        fi

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.xcresult