name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    name: Code Quality
    runs-on: macos-15
    
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: Install Tools
      run: brew install swiftlint swiftformat
      
    - name: SwiftFormat Check (formatting authority)
      run: swiftformat --lint .
      
    - name: SwiftLint Check (code quality only)
      run: swiftlint --strict

  build-and-test:
    name: Build & Test
    runs-on: macos-15
    
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      # Enable Tuist cloud features with authentication
      CI: 1
      TUIST_CONFIG_TOKEN: ${{ secrets.TUIST_CONFIG_TOKEN }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: Install Tuist
      run: |
        brew tap tuist/tuist
        brew install --formula tuist
        tuist version
    - name: Cache Tuist dependencies
      uses: actions/cache@v4
      with:
        path: |
          Tuist/.build
          ~/.cache/tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('Tuist/Package.swift', 'Tuist/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-tuist-
      
    - name: Install dependencies
      run: tuist install
      
    - name: Build and test with Tuist
      run: |
        # tuist build generates project implicitly and builds
        tuist build App
        # tuist test also generates implicitly if needed
        tuist test App --result-bundle-path test-results.xcresult

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.xcresult