name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-format:
    name: Code Quality
    runs-on: macos-15
    
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
      
    - name: Install Tools
      run: brew install swiftlint swiftformat
      
    - name: SwiftFormat Check (formatting authority)
      run: swiftformat --lint .
      
    - name: SwiftLint Check (code quality only)
      run: swiftlint --strict

  build-and-test:
    name: Build & Test
    runs-on: macos-15
    
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
      # Disable Tuist cloud features - using local builds only
      CI: 1
    
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      
    - name: Select Xcode 16.4
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.4'
      
    - name: Install Tuist
      run: |
        brew tap tuist/tuist
        brew install --formula tuist
        tuist version
    - name: Cache Tuist dependencies
      uses: actions/cache@v4
      with:
        path: |
          Tuist/.build
          ~/.cache/tuist
        key: ${{ runner.os }}-tuist-${{ hashFiles('Tuist/Package.swift', 'Tuist/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-tuist-
      
    - name: Validate CI environment
      run: ./Scripts/validate-ci-environment.sh
      
    - name: Skip Xcode Macro Fingerprint Validation
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
      
    - name: Skip Xcode Package Validation
      run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
      
    - name: Setup reliable simulator
      run: |
        chmod +x ./Scripts/ci-pick-simulator.sh
        ./Scripts/ci-pick-simulator.sh
      
    - name: Install dependencies
      run: tuist install
      
    - name: Generate project
      run: tuist generate --no-open
      
    - name: Build with explicit destination
      run: |
        xcodebuild build \
          -workspace iOSClaudeCodeStarter.xcworkspace \
          -scheme App \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -destination-timeout 180 \
          -skipPackagePluginValidation \
          -skipMacroValidation
          
    - name: Test with explicit destination
      run: |
        xcodebuild test \
          -workspace iOSClaudeCodeStarter.xcworkspace \
          -scheme App \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -destination-timeout 180 \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          -resultBundlePath test-results.xcresult

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results.xcresult